name: goalzone
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flame: ^1.29.0
  flame_audio: ^2.11.6
  flame_forge2d: ^0.19.0+2
  google_fonts: ^6.2.1
  hive: ^2.2.3
  path_provider: ^2.1.5
  rive: ^0.13.20
  vibration: ^3.1.3
  # vibration plugin kaldırıldı; yerleşik HapticFeedback kullanılacak
  # vibration: ^1.7.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audio/hit.wav
    - assets/audio/goal.wav
